# Generated by Django 6.0.1 on 2026-01-28 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='', help_text='주소', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='boss_name',
            field=models.CharField(default='', help_text='대표자 이름', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='business_file',
            field=models.FileField(default='', upload_to='business_files/', verbose_name='사업자 등록증 파일'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(default='', help_text='사업자 명', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='company_number',
            field=models.CharField(default='', help_text='사업자 번호', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='detail_address',
            field=models.CharField(default='', help_text='상세주소', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='', help_text='이메일', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='email_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='extraAddress',
            field=models.CharField(default='', help_text='주소 참고 사항', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='manager_name',
            field=models.CharField(default='', help_text='담당자 이름', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='message_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='', help_text='전화 번호', max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='post_code',
            field=models.CharField(default='', help_text='우편 번호', max_length=20),
            preserve_default=False,
        ),
    ]
