# Generated by Django 6.0.1 on 2026-01-28 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_address_user_boss_name_user_business_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Excel_upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_file', models.FileField(upload_to='excel_files/', verbose_name='엑셀 주문 파일')),
                ('company_name', models.CharField(help_text='주문 사업자 이름', max_length=30)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excel_uploads', to=settings.AUTH_USER_MODEL, verbose_name='업로드 사용자')),
            ],
        ),
    ]
