# Generated by Django 6.0.1 on 2026-01-28 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_excel_upload'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Excel_upload',
            new_name='ExcelUpload',
        ),
        migrations.RenameField(
            model_name='excelupload',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='excelupload',
            old_name='user_id',
            new_name='user',
        ),
    ]
