# Generated by Django 6.0.1 on 2026-02-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_num', models.CharField(max_length=50)),
                ('item_title', models.CharField(max_length=150)),
                ('item_desc', models.TextField(blank=True, null=True)),
                ('item_cate', models.CharField(choices=[('농산물', '농산물'), ('수산물', '수산물'), ('축산물', '축산물'), ('가공식품', '가공식품'), ('김치', '김치'), ('젓갈', '젓갈'), ('기타', '기타')], max_length=10)),
                ('select_tex', models.CharField(max_length=5)),
                ('item_price', models.PositiveIntegerField()),
                ('item_origin', models.CharField(choices=[('과세', '과세'), ('면세', '면세')], max_length=20)),
                ('delivery_1', models.PositiveIntegerField()),
                ('delivery_2', models.PositiveIntegerField()),
            ],
        ),
    ]
