# Generated by Django 6.0.1 on 2026-02-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_num',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_origin',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='select_tex',
            field=models.CharField(choices=[('과세', '과세'), ('면세', '면세')], max_length=5),
        ),
    ]
