# Generated by Django 6.0.1 on 2026-02-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_created_at_item_updated_at_alter_item_item_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_status',
            field=models.CharField(choices=[('stop', '중지'), ('sale', '판매중')], default='sale', max_length=5),
        ),
    ]
