# Generated by Django 6.0.1 on 2026-02-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_thumnbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumnbnail',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
