# Generated by Django 6.0.1 on 2026-02-27 05:19

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_thumnbnail_is_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='상품 설명'),
        ),
    ]
