# Generated by Django 6.0.1 on 2026-01-30 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='회사 명', max_length=100)),
                ('deposit_value', models.PositiveIntegerField(help_text='입금 신청 금액')),
                ('deposit_name', models.CharField(help_text='입금 신청자 명', max_length=50)),
                ('deposit_status', models.CharField(choices=[('pending', '입금대기'), ('confirmed', '입금완료'), ('rejected', '반려')], default='pending', help_text='입금 상태', max_length=10)),
                ('is_applied', models.BooleanField(default=False, help_text='입금 중복 방지 장치')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='입금 신청 시간')),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='입금 승인 시간', null=True)),
                ('admin_memo', models.TextField(blank=True, help_text='관리자 메모용')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
