# Generated by Django 6.0.1 on 2026-02-01 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_wallet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(help_text='은행 명', max_length=10)),
                ('user_name', models.CharField(help_text='예금주', max_length=5)),
                ('bank_num', models.CharField(help_text='계좌번호', max_length=50)),
                ('refund_value', models.PositiveIntegerField(help_text='환급 금액')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
