# Generated by Django 6.0.1 on 2026-02-01 03:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='admin_memo',
            field=models.TextField(blank=True, help_text='관리자 메모용'),
        ),
        migrations.AddField(
            model_name='refund',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
