# Generated by Django 6.0.1 on 2026-02-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_refund_admin_memo_refund_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, help_text='환급 승인 시간', null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='is_applied',
            field=models.BooleanField(default=False, help_text='환급 중복 방지 장치'),
        ),
        migrations.AddField(
            model_name='refund',
            name='refund_status',
            field=models.CharField(choices=[('pending', '대기'), ('confirmed', '완료'), ('rejected', '반려')], default='pending', help_text='환급 상태', max_length=10),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='deposit_status',
            field=models.CharField(choices=[('pending', '대기'), ('confirmed', '완료'), ('rejected', '반려')], default='pending', help_text='입금 상태', max_length=10),
        ),
        migrations.AlterField(
            model_name='refund',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='신청 시간'),
        ),
    ]
