# Generated by Django 6.0.1 on 2026-01-29 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.CharField(help_text='주문번호', max_length=20, unique=True)),
                ('status', models.CharField(choices=[('READY', '상품준비중'), ('SHIPPING', '배송중'), ('DONE', '배송완료'), ('CANCEL', '취소')], default='READY', max_length=10)),
                ('product_name', models.CharField(help_text='상품명', max_length=100)),
                ('option_name', models.CharField(help_text='상품 옵션', max_length=50)),
                ('quantity', models.PositiveIntegerField(help_text='구매 수량')),
                ('receiver_name', models.CharField(help_text='수취인 이름', max_length=20)),
                ('receiver_phone', models.CharField(help_text='수취인 번호', max_length=20)),
                ('post_code', models.CharField(help_text='우편 번호', max_length=10)),
                ('address', models.CharField(help_text='주소', max_length=255)),
                ('delivery_msg', models.CharField(blank=True, help_text='배송 메세지', max_length=255)),
                ('order_name', models.CharField(help_text='주문자 이름', max_length=20)),
                ('order_phone', models.CharField(help_text='주문자 번호', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='주문 날짜')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
